Repository SNL-WaterPower/WecOptTool, pull requests merged in 2020-04, with the labels that each got.

#119 Add Docs Versioning
  .travis.yml
  .travis/key.enc
  README.md
  docs/make_www_local.bat
  docs/make_www_remote.bat
  docs/makefile
Labels: documentation, enhancement

#124 fix line number refs to example.m
  docs/user/example.rst
Labels: bug, documentation

#129 Consider Sea States Frequency Range in Hydrodynamics
  example.m
  toolbox/+WecOptLib/+models/+RM3/@DeviceModel/getHydrodynamics.m
  toolbox/+WecOptLib/+models/DeviceModelTemplate.m
  toolbox/+WecOptLib/+tests/+unit/RM3DeviceModelParametricCCTest.m
  toolbox/+WecOptLib/+tests/+unit/RM3DeviceModelTest.m
  toolbox/+WecOptLib/+tests/+unit/checkSpectrumTest.m
  toolbox/+WecOptLib/+tests/+unit/seaStatesGlobalWTest.m
  toolbox/+WecOptLib/+utils/checkSpectrum.m
  toolbox/+WecOptLib/+utils/seaStatesGlobalW.m
  toolbox/+WecOptTool/+geom/AbsGeom.m
  toolbox/+WecOptTool/+geom/Existing.m
  toolbox/+WecOptTool/+geom/Parametric.m
  toolbox/+WecOptTool/+geom/Scalar.m
  toolbox/+WecOptTool/RM3Study.m
  toolbox/+WecOptTool/plot.m
  toolbox/+WecOptTool/run.m
Labels: cleanup/useability, enhancement
