Repository SNL-WaterPower/WecOptTool, pull requests merged in 2020-09, with the labels that each got.

#163 WaveBot Case C
  examples/WaveBot/WaveBot_caseB.m
  examples/WaveBot/WaveBot_caseC.m
Labels: examples

#169 WaveBot README
  examples/WaveBot/README.md
  examples/WaveBot/WaveBot_caseA.m
  examples/WaveBot/WaveBot_caseB.m
  examples/WaveBot/WaveBot_caseC.m
Labels: documentation

#168 docs for creating new models
  .travis.yml
  README.md
  docs/_static/WecOptToolFlowChartCode.svg
  docs/_static/theme_overrides.css
  docs/conf.py
  docs/contents.rst
  docs/user/WecOptTool_refs.bib
  docs/user/model.rst
  docs/user/optimization.rst
  docs/user/references.rst
Labels: documentation

#177 Remove call to struct2array
  examples/RM3/designDevice.m
Labels: bug

#180 Update Index Page for Version 1.0
  docs/index.rst
  docs/user/optimization.rst
Labels: documentation

#181 Fix details not being unrolled when clicking on summary in Chrome
  docs/_static/theme_overrides.css
  docs/user/model.rst
  docs/user/optimization.rst
  docs/user/setup.rst
  toolbox/+WecOptTool/AutoFolder.m
  toolbox/+WecOptTool/SeaState.m
Labels: bug, documentation
